### PR TITLE
Update for grunt 0.4 and add missing dependancies

### PR DESCRIPTION
**Pull request by rpaskowitz**
Switches to contrib- packages and new grunt 0.4 formatting.

### CODE REVIEW

**Comment by jasondscott** [comment]
Hi @rpaskowitz 
It looks like you haven't signed our CLA. Everyone must sign a CLA before we can accept any code.
Here are the links to the CLA's. One If you a [Individual](http://www.blackberry.com/legal/pdfs/webworks/Research_In_Motion_Limited_ICLA_021811_cl.pdf) and one if you are a [Corporation](http://www.blackberry.com/legal/pdfs/webworks/Research_In_Motion_Limited_CCLA_021811_cl.pdf).

Could you sign one and summit it?
Check out http://blackberry.github.com/howToContribute.html for more information.

Thanks

**Comment by rpaskowitz** [comment]
@jasondscott , CLA has now been sent to githib@rim.com

**Comment by jasondscott** [comment]
Thanks @rpaskowitz 
I just need to hear back from the team that processes them now. Shouldn't be long.

**Comment by jasondscott** [comment]
Hi @rpaskowitz we just tried out your change and it doesn't seem to be compiling all of the files correctly. 
We are going to merge in #113 which should have all of these fixes in it too. 
Please try it out after it has merged and let us know if it is missing something.
I look forward to seeing more future development from you.
Thanks for the contribution!

**Pull request closed without merging**
