### PR TITLE
Updating GitHub pages branch

### LINKED ISSUE #55: GitHub Pages
Branch should be updated to reflect latest changes.

### PR DESCRIPTION
**Pull request by mdabydeen**
Fixes #55 .

### CODE REVIEW

**Comment by mdabydeen** [comment]
@jasondscott your thoughts?

**Comment by jasondscott** [comment]
Can you also (on master)
- increase the version number to 0.9.1
- run `grunt release`
- Add the new dist/0.9.1 folder to github
- Cherry pick the above in this PR

Then we can merge it in.

**Comment by mdabydeen** [comment]
@jasondscott  this is done. What should we do with dist/0.9.0 ?

**Comment by jasondscott** [comment]
@mdabydeen dist/0.9.0 will remain as it is.

**Pull request merged**
